name: flutter_app
description: "A pet adoption and lost & found application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  js: ^0.6.7
  cupertino_icons: ^1.0.8
  google_mobile_ads: ^5.0.0

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  google_sign_in: ^7.2.0

  # File & Image
  image_picker: ^1.0.4
  file_picker: ^10.3.7
  flutter_image_compress: ^2.4.0
  path: ^1.9.0
  path_provider: ^2.1.3

  # Location
  geolocator: ^14.0.2
  geocoding: ^3.0.0

  # UI & Utils
  cached_network_image: ^3.3.0
  provider: ^6.1.1
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  url_launcher: ^6.2.1
  intl: ^0.19.0

  # Charts
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
